# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N6a-UH1gwnrTSzHxvbQ7vWczQ9XwRdvG
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv("/content/train.txt", header=None, sep=";" ,names=["text","emotion"])

df.head()

df.info()

df.isnull().sum()

unique_emotion=df['emotion'].unique()

unique_emotion

unique_text=df['text'].unique()
emotion_number={}
it=0;
for i in unique_emotion:
  emotion_number[i]=it;
  it+=1;

df["emotion"]=df["emotion"].map(emotion_number)

df
df['text']=df['text'].apply( lambda x: x.lower())

df

import string
def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

df['text']=df['text'].apply(remove_punc)

def remove_numbers(txt):
  new=''
  for i in txt:
    if not i.isdigit():
      new +=i
  return new
df['text']=df['text'].apply(remove_numbers)

def remove_emojis(txt):
  new=''
  for i in txt:
    if i.isascii():
      new += i
  return new
df['text']= df['text'].apply(remove_emojis)



df

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import  word_tokenize

nltk.download('punkt')
nltk.download('stopwords')

stop_words= set(stopwords.words('english'))

df.loc[1]['text']

def remove(txt):
  words= txt.split()
  cleaned= []
  for i in words:
    if not i in stop_words:
      cleaned.append(i)
  return " ".join(cleaned)
df['text']=df['text'].apply(remove)

df
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vetorizer=CountVectorizer()
x_train_bow=bow_vetorizer.fit_transform(x_train)
x_test_bow=bow_vetorizer.transform(x_test)

nb_model=MultinomialNB()
nb_model.fit(x_train_bow,y_train)

pred_bow=nb_model.predict(x_test_bow)
# accuracy_score(y_test,pred_bow)
print(accuracy_score(y_test,pred_bow))

pred_bow

from sklearn.linear_model import LogisticRegression

lr_model=LogisticRegression(max_iter=1000)
lr_model.fit(x_train_bow,y_train)

pred_lr=lr_model.predict(x_test_bow)
print(accuracy_score(y_test,pred_lr))

